import { StyleSheet } from 'react-native';
import { Spacing, BorderRadius } from '@/constants/theme';

export const createStyles = () => {
  return StyleSheet.create({
    scrollContent: {
      flexGrow: 1,
    },
    header: {
      marginBottom: Spacing.xl,
    },
    headerGradient: {
      paddingVertical: Spacing.xl,
      paddingHorizontal: Spacing.xl,
      alignItems: 'center',
      borderBottomLeftRadius: 32,
      borderBottomRightRadius: 32,
    },
    title: {
      marginTop: Spacing.md,
      textAlign: 'center',
    },
    subtitle: {
      marginTop: Spacing.sm,
      textAlign: 'center',
      opacity: 0.9,
    },
    petName: {
      fontSize: 28,
      fontWeight: '700',
    },
    petType: {
      marginTop: Spacing.sm,
      opacity: 0.9,
    },
    section: {
      paddingHorizontal: Spacing.xl,
      marginBottom: Spacing.xl,
    },
    sectionTitle: {
      marginBottom: Spacing.lg,
    },
    modulesContainer: {
      gap: Spacing.md,
    },
    moduleCard: {
      borderRadius: BorderRadius.lg,
      overflow: 'hidden',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
    },
    moduleGradient: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: Spacing.lg,
    },
    moduleIcon: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    moduleInfo: {
      flex: 1,
      marginLeft: Spacing.md,
    },
    moduleArrow: {
      opacity: 0.8,
    },
    petTypeCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      padding: Spacing.lg,
      borderRadius: BorderRadius.lg,
      marginBottom: Spacing.md,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    petTypeIcon: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: '#F0F0F3',
      alignItems: 'center',
      justifyContent: 'center',
    },
    petTypeInfo: {
      flex: 1,
      marginLeft: Spacing.md,
    },
    petAvatarContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      height: 220,
      marginBottom: Spacing.xl,
    },
    petAvatarWrapper: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    petAvatar: {
      shadowColor: '#6C63FF',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.2,
      shadowRadius: 20,
      elevation: 5,
    },
    statusBadge: {
      marginTop: Spacing.md,
      paddingHorizontal: Spacing.lg,
      paddingVertical: Spacing.sm,
      backgroundColor: '#6C63FF',
      borderRadius: 20,
    },
    houseScene: {
      borderRadius: BorderRadius.lg,
      overflow: 'hidden',
      shadowColor: '#F39C12',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
      elevation: 5,
    },
    houseGradient: {
      height: 200,
      position: 'relative',
      justifyContent: 'center',
      alignItems: 'center',
    },
    houseBackground: {
      position: 'absolute',
      top: 10,
      right: 10,
      opacity: 0.15,
    },
    houseStructure: {
      position: 'relative',
      alignItems: 'center',
    },
    chimney: {
      position: 'absolute',
      top: -30,
      right: -10,
      transform: [{ rotate: '-10deg' }],
    },
    houseBody: {
      position: 'relative',
    },
    houseDoor: {
      position: 'absolute',
      bottom: -10,
      left: 30,
    },
    houseWindow: {
      position: 'absolute',
      top: -10,
      right: -5,
    },
    housePet: {
      position: 'absolute',
      bottom: 20,
      left: 50,
      zIndex: 10,
    },
    petInHouse: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: '#FFFFFF',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 6,
      elevation: 3,
    },
    petShadow: {
      position: 'absolute',
      bottom: -5,
      left: 10,
      width: 30,
      height: 6,
      backgroundColor: 'rgba(0, 0, 0, 0.15)',
      borderRadius: 3,
    },
    decorations: {
      position: 'absolute',
      width: '100%',
      height: '100%',
    },
    tree: {
      position: 'absolute',
      bottom: 10,
      right: 20,
    },
    sun: {
      position: 'absolute',
      top: 10,
      right: 60,
    },
    cloud: {
      position: 'absolute',
      top: 20,
      left: 30,
    },
    clickHint: {
      position: 'absolute',
      bottom: 10,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.2)',
      paddingHorizontal: Spacing.md,
      paddingVertical: 6,
      borderRadius: 20,
    },
    statsContainer: {
      gap: Spacing.lg,
    },
    statItem: {
      backgroundColor: '#FFFFFF',
      padding: Spacing.lg,
      borderRadius: BorderRadius.lg,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 1,
    },
    statHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: Spacing.sm,
    },
    statBar: {
      height: 8,
      backgroundColor: '#F0F0F3',
      borderRadius: 4,
      overflow: 'hidden',
      marginBottom: Spacing.sm,
    },
    statBarFill: {
      height: '100%',
      borderRadius: 4,
    },
    actionsContainer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      gap: Spacing.md,
    },
    actionButton: {
      flex: 1,
      aspectRatio: 1,
      borderRadius: BorderRadius.lg,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 3,
    },
  });
};
